---
language: python
python:
  - 3.6
before_install:
 - pip install -r requirement.txt

virtualenv:
    system_site_package: true
    
script:
 - pip freeze
notifications:
  email: 
    - ahmed.zenakhi@gmail.com
