---
language: python
python:
  - 3.6
before_install:
 - pip install -r requirements.txt

virtualenv:
    system_site_package: true
    
script:
 - python -m 'json'
notifications:
  email: 
    - ahmed.zenakhi@gmail.com
