language: go
go:
  - "1.13"
  
env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}
    - REPO=azenakhi/jenkinsci

script:
  - docker build -f Dockerfile -t $REPO:$COMMIT .

after_success:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then cat Version; else (echo $TRAVIS_BRANCH) ; fi`
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker push $REPO:$TAG
